name: universal_dropdown
description: A highly customizable and generic dropdown widget for Flutter supporting single/multi selection, search, and custom item widgets.

version: 1.0.8
homepage: https://github.com/hanifinno/universal_dropdown
repository: https://github.com/hanifinno/universal_dropdown.git
issues: https://github.com/hanifinno/universal_dropdown/issues


environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
